-- NotaDez - Esquema Simplificado
-- Sistema para gerenciamento de notas por professores
-- Projeto Integrador II - Engenharia de Software

/* ========================
   Tabelas principais
   ======================== */

CREATE TABLE usuarios (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome          VARCHAR2(150)       NOT NULL,
  email         VARCHAR2(255)       NOT NULL,
  telefone      VARCHAR2(20),
  senha_hash    VARCHAR2(255)       NOT NULL,
  criado_em     TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE usuarios IS 'Armazena dados de PROFESSORES/DOCENTES que acessam o sistema NotaDez. Alunos NÃO são usuários.';

ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_email UNIQUE (email);

CREATE TABLE instituicoes (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  usuario_id    NUMBER               NOT NULL,
  nome          VARCHAR2(255)        NOT NULL,
  criado_em     TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_instituicoes_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE cursos (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  instituicao_id   NUMBER               NOT NULL,
  nome             VARCHAR2(255)        NOT NULL,
  criado_em        TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_cursos_instituicao
    FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id)
);

CREATE TABLE disciplinas (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  curso_id       NUMBER               NOT NULL,
  codigo         VARCHAR2(50),
  nome           VARCHAR2(255)        NOT NULL,
  sigla          VARCHAR2(20)         NOT NULL,
  periodo        NUMBER(3),
  criado_em      TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_disciplinas_curso
    FOREIGN KEY (curso_id) REFERENCES cursos(id)
);

ALTER TABLE disciplinas ADD CONSTRAINT uk_disciplinas_curso_sigla UNIQUE (curso_id, sigla);

CREATE TABLE turmas (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  disciplina_id  NUMBER               NOT NULL,
  nome           VARCHAR2(255)        NOT NULL,
  criado_em      TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_turmas_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);

CREATE TABLE alunos (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  usuario_id    NUMBER               NOT NULL, -- FK para o professor que cadastrou este aluno
  identificador VARCHAR2(50)         NOT NULL, -- RA/Matrícula/ID
  nome          VARCHAR2(255)        NOT NULL,
  criado_em     TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_alunos_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) -- Referência ao professor (docente)
);

COMMENT ON COLUMN alunos.usuario_id IS 'Referencia o professor/docente que cadastrou este aluno. Alunos NÃO fazem login no sistema.';

ALTER TABLE alunos ADD CONSTRAINT uk_alunos_usuario_ident UNIQUE (usuario_id, identificador);

CREATE TABLE turmas_alunos (
  id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  turma_id   NUMBER              NOT NULL,
  aluno_id   NUMBER              NOT NULL,
  CONSTRAINT fk_ta_turma FOREIGN KEY (turma_id) REFERENCES turmas(id),
  CONSTRAINT fk_ta_aluno FOREIGN KEY (aluno_id) REFERENCES alunos(id),
  CONSTRAINT uk_ta_turma_aluno UNIQUE (turma_id, aluno_id)
);

CREATE TABLE componentes_nota (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  disciplina_id  NUMBER               NOT NULL,
  sigla          VARCHAR2(20)         NOT NULL,
  nome           VARCHAR2(255)        NOT NULL,
  peso           NUMBER(4,3)          DEFAULT 0 NOT NULL,
  criado_em      TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_compn_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id),
  CONSTRAINT ck_compn_peso CHECK (peso >= 0 AND peso <= 1)
);

ALTER TABLE componentes_nota ADD CONSTRAINT uk_compn_disc_sigla UNIQUE (disciplina_id, sigla);

CREATE TABLE notas (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  turma_id        NUMBER NOT NULL,
  aluno_id        NUMBER NOT NULL,
  componente_id   NUMBER NOT NULL,
  valor           NUMBER(4,2),
  atualizado_por  NUMBER NOT NULL,
  atualizado_em   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_notas_turma       FOREIGN KEY (turma_id)      REFERENCES turmas(id),
  CONSTRAINT fk_notas_aluno       FOREIGN KEY (aluno_id)      REFERENCES alunos(id),
  CONSTRAINT fk_notas_componente  FOREIGN KEY (componente_id) REFERENCES componentes_nota(id),
  CONSTRAINT fk_notas_user        FOREIGN KEY (atualizado_por) REFERENCES usuarios(id),
  CONSTRAINT ck_notas_valor CHECK (valor IS NULL OR (valor >= 0 AND valor <= 10))
);

/* ========================
   Índices auxiliares
   ======================== */
CREATE INDEX ix_cursos_instituicao    ON cursos(instituicao_id);
CREATE INDEX ix_disc_curso            ON disciplinas(curso_id);
CREATE INDEX ix_turmas_disciplina     ON turmas(disciplina_id);
CREATE INDEX ix_alunos_usuario        ON alunos(usuario_id);
CREATE INDEX ix_ta_turma              ON turmas_alunos(turma_id);
CREATE INDEX ix_ta_aluno              ON turmas_alunos(aluno_id);
CREATE INDEX ix_compn_disciplina      ON componentes_nota(disciplina_id);
CREATE INDEX ix_notas_turma           ON notas(turma_id);
CREATE INDEX ix_notas_aluno           ON notas(aluno_id);
CREATE INDEX ix_notas_componente      ON notas(componente_id);

/* ========================
   Trigger de auditoria - Simplificado
   ======================== */

CREATE OR REPLACE TRIGGER trg_notas_audit
AFTER INSERT OR UPDATE ON notas
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO auditoria_notas (aluno_id, componente_id, valor_antigo, valor_novo)
    VALUES (:NEW.aluno_id, :NEW.componente_id, NULL, :NEW.valor);
  ELSIF UPDATING THEN
    INSERT INTO auditoria_notas (aluno_id, componente_id, valor_antigo, valor_novo)
    VALUES (:NEW.aluno_id, :NEW.componente_id, :OLD.valor, :NEW.valor);
  END IF;
END;
/

-- Fim do schema
