-- NotaDez - Tabela de Tokens de Recuperação de Senha
-- Projeto Integrador II - Sistema de recuperação de senha por e-mail

-- Tabela para armazenar tokens temporários de recuperação
CREATE TABLE tokens_recuperacao (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  usuario_id     NUMBER               NOT NULL,
  token          VARCHAR2(255)        NOT NULL,
  expira_em      TIMESTAMP            NOT NULL,
  usado          NUMBER(1)            DEFAULT 0 NOT NULL,
  criado_em      TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT ck_tokens_usado CHECK (usado IN (0, 1))
);

COMMENT ON TABLE tokens_recuperacao IS 'Armazena tokens temporários para recuperação de senha via e-mail';
COMMENT ON COLUMN tokens_recuperacao.token IS 'Token único gerado (UUID ou hash)';
COMMENT ON COLUMN tokens_recuperacao.expira_em IS 'Data/hora de expiração do token (geralmente 1 hora após criação)';
COMMENT ON COLUMN tokens_recuperacao.usado IS '0 = não usado, 1 = já utilizado';

-- Índices para performance
CREATE INDEX ix_tokens_usuario ON tokens_recuperacao(usuario_id);
CREATE INDEX ix_tokens_expira ON tokens_recuperacao(expira_em);

-- Restrição única para garantir que cada token é único
ALTER TABLE tokens_recuperacao
  ADD CONSTRAINT uq_tokens_token UNIQUE (token);

-- Trigger para limpeza automática de tokens expirados (executa a cada INSERT)
-- Isso garante que tokens antigos sejam removidos automaticamente
CREATE OR REPLACE TRIGGER trg_limpar_tokens_expirados
AFTER INSERT ON tokens_recuperacao
BEGIN
  -- Remove tokens expirados há mais de 24 horas
  DELETE FROM tokens_recuperacao 
  WHERE expira_em < SYSTIMESTAMP - INTERVAL '24' HOUR;
END;
/

-- Verificar criação
SELECT 'Tabela tokens_recuperacao criada com sucesso!' AS status FROM dual;
